name: Deploy Dev

on:
  push:
    branches: ["development"]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'

    #  - name: Install Entity Framework Core Tools
    #    run: dotnet tool install --global dotnet-ef

    #  - name: Run Entity Framework Core Migrations
    #    run: /aitrainer-backend/AITrainer/dotnet ef database update --project AITrainer.csproj --startup-project AITrainer.csproj
    #    env:
    #      CONNECTION_STRING: ${{ secrets.YOUR_CONNECTION_STRING_SECRET_NAME }}
    
      - name: Build with dotnet
        run: dotnet build --configuration Release


      - name: Copy src Folder to Remote Server
        uses: appleboy/scp-action@v0.1.4
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            source: "."
            target: "/root/aitrainer-backend"

      - name: Build and Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |
                cd aitrainer-backend
                export COMPOSE_INTERACTIVE_NO_CLI=1
                sudo docker-compose up -d --force-recreate --build aitrainer-api
