export const StringConstant = {
    someErrorOccuredPleaseTryAgainLater: 'Some error occured.Please try again later!',
    internName: 'Intern Name',
    startDate: 'Start Date',
    endDate: 'End Date',
    type: 'Type',
    totalDays: 'Total Days',
    approvalStatus: 'Approval Status',
    pending: 'Pending',
    approved: 'Approved',
    rejected: 'Rejected',
    none: 'None',
    appliedDate: 'Applied Date',
    reasonForLeave: 'Reason For Leave',
    updatedBy: 'Updated By',
    action: 'Action',
    approve: 'Approve',
    reject: 'Reject',
    noLeaveRecords: 'No Leave Records',
    approveLeave: 'Approve Leave',
    youAreAboutTo: 'You are about to',
    leaveDoYouWantToProceed: 'leave. Do you want to proceed?',
    reason: 'Reason',
    rejectLeave: 'Reject Leave',
    leaveRequest: 'Leave Request',
    leaveType: 'Leave Type',
    leaveTypeIsRequired: 'Leave Type is required',
    selectLeaveType: 'Select Leave Type',
    enterValidReason: 'Enter a valid reason',
    requestAttendance: 'Request Attendance:',
    name: 'Name',
    date: 'Date',
    punches: 'Punches',
    requestedDate: 'Requested Date',
    requestReason: 'Request Reason',
    status: 'Status',
    noRequestedRecords: 'No Requested Records',
    approveRequest: 'Approve Request',
    rejectRequest: 'Reject Request',
    requestDoYouwantToProceed: 'Request. do you want to proceed?',
    saveChanges: 'Save Changes',
    close: 'Close',
    cancel: 'Cancel',
    attendanceDate: 'Attendance Date :',
    comment: 'Comment',
    reset: 'Reset',
    request: 'Request',
    attendanceDetails: 'Attendance Details',
    totalHours: 'Total Hours',
    requestPunch: 'Request Punch',
    applyLeave: 'Apply Leave',
    areYouSureYouWantToDelete: 'Are you sure you want to Delete',
    deleteRequestRecord: 'Delete Request Record',
    delete: 'Delete',
    requested: 'Requested',
    invalidTimeFormatPleaseEnterTimeInHHmmFormat: 'Invalid time format. Please enter time in HH:mm format.',
    endDateShouldBeGreaterThanStartDate: 'End date should be greater than start date.',
    leaveHasAlreadyBeenAppliedForSimilarPeriod: 'Leave has already been applied for similar period.',
    leaveCanNotAppliedOnHoliday: 'Company has defined a holiday on this date. Therefore, leave cannot be applied for this day.',
    leavePeriod: 'Leave Period',
    halfDayLeave: 'Half day leave',
    attachment: 'Attachment',
    addAttachment: 'Add Attachment',
    invalidFormatUseHHmmOrHHmmHHmme091830: 'Invalid format. Use HH:mm format. (e.g., 9:00, 18:30).',
    punchTimesAreRequired: 'Punch times are required.',
    pleaseEnterPunchesIn24HoursFormateg9001830PressEnterAfterPuttingEachPunch: 'Please enter punches in 24 hours format eg. 9:00, 18:30. Press enter after putting each punch.',
    punchesShouldBeInChronologicalSequenceDoNotUseAnyStringsLikeAMPMEtc: 'Punches should be in chronological sequence. Do not use any strings like AM, PM, etc.',
    intern: 'Intern',
    applied: '(Applied)',
    firstHalf: 'First Half',
    secondHalf: 'Second Half',
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
    leaveDetails: 'Leave Details',
    checkOut: 'Check Out',
    checkIn: 'Check In',
    history: 'History',
    courses: 'Courses',
    journalTemplate: 'Journal Template',
    internships: 'Internships',
    organization: 'Organization',
    batch: 'Batch',
    scoreboard: 'Scoreboard',
    attendance: 'Attendance',
    leaves: 'Leaves',
    behaviouralTemplate: 'Behavioural Template',
    leaveRequests: 'Leave Requests',
    mentorDashboard: 'Mentor Dashboard',
    feedbackDashboard: 'Feedback Dashboard',
    bugsAndFeedbacks: 'Bugs & Feedbacks',
    careerPath: 'Career Path',
    youHaveAlreadyRequestOnThisDate: 'You Have Already Requested On This Date',
    holiday: 'Holiday',
    nationalHolidays: 'National Holidays:',
    srNo: 'Sr. No.',
    weekDays: 'Week Days',
    holidays: 'Holidays',
    workLocation: 'Work Location',
    noHolidaytoShow: 'No Holiday to Show',
    attachmentDetails: 'Attachment Details',
    undefined: 'undefined',
    popupBlockedByTheBrowser: 'Popup blocked by the browser.',
    smallAttachment: 'attachment',
    smallAttachments: 'attachments',
    leaveAttachments: 'Leave Attachments',
    templateDeleteSuccess: 'Template Deleted Successfully!!',
    deleteCourse: 'Delete Course',
    areYousureText: 'Are you sure you want to delete?',
    fractionalHours: 'Fractional hours can not be applied',
    noDataDownload: 'No scores added to download',
    deleteAdmin: 'Delete Admin',
    deleteTemplate: 'Delete Template',
    deleteQuestion: 'Delete Question',
    deleteTopic: 'Delete Topic',
    deleteJournal: 'Delete Journal',
    all: 'All',
    areYouSureYouWantToEnableAdmin: 'Are you sure you want to Enable Admin ?',
    enable: 'Enable',
    update: 'Update',
    filterBatch: 'Filter Batch',
    passwordIsRequired: 'Password is required.',
    passwordShouldContainAtLeastOneCapitalLetterANumberAndASpecialCharacter: 'Password must be at least 8 characters long and contain at least one uppercase letter, one number, and one special character.',
    confirmPassword: 'Confirm Password:',
    confirmPasswordIsRequired: 'Confirm Password is required.',
    passwordsDoNotMatch: 'Passwords do not match.',
    createPassword: 'Create Password',
    createYourPassword: 'Create Your Password',
    password: 'Password:',
    resetPassword: 'Reset Password',
    newPassword: 'New Password:',
    workFromHome: 'Work From Home',
    casualLeave: 'Casual Leave',
    sickLeave: 'Sick Leave',
    wfh: '(WFH)',
    ok: 'OK',

}